"""teste1

Revision ID: 7c67f84e80ce
Revises: 
Create Date: 2023-10-29 00:29:54.336875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c67f84e80ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cliente_id', table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cliente_id', 'cliente', ['id'], unique=False)
    # ### end Alembic commands ###
